// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saving_Accelerator_Tool.Data;

namespace Saving_Accelerator_Tool.Migrations
{
    [DbContext(typeof(DataBaseConnectionContext))]
    partial class DataBaseConnectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Saving_Accelerator_Tool.Model.UserDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ActionEle")
                        .HasColumnType("bit");

                    b.Property<bool>("ActionMech")
                        .HasColumnType("bit");

                    b.Property<bool>("ActionNVR")
                        .HasColumnType("bit");

                    b.Property<bool>("ActionTab")
                        .HasColumnType("bit");

                    b.Property<bool>("AdminTab")
                        .HasColumnType("bit");

                    b.Property<bool>("ElectronicApprove")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MechanicApprove")
                        .HasColumnType("bit");

                    b.Property<bool>("NVRApprove")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PCApprove")
                        .HasColumnType("bit");

                    b.Property<bool>("PlatformTab")
                        .HasColumnType("bit");

                    b.Property<bool>("QuantityTab")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("STKTab")
                        .HasColumnType("bit");

                    b.Property<bool>("StatisticTab")
                        .HasColumnType("bit");

                    b.Property<bool>("SummaryTab")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
